* Macro to estimate spectrum of the residuals after de-trending using Kalman filter;

%macro perisers(cent,repunit,var);
data work.centre;
   set work.res; * Use residuals from smooth above; 
   if centre=&cent. and runit in (&repunit.); 
run;
proc spectra data=work.centre out=work.peri p adjmean;
   by centre runit;
   var errs;
run;
* Get the variance for standardising;
proc univariate data=work.centre noprint;
   var errs;
   output out=work.errvar var=errvar;
run;
* Estimate the spectrum & standardise the periodogram;
proc iml;
   use work.peri var{centre runit period freq p_01};
   read all;
   use work.errvar var{errvar};
   read all;
   n=nrow(centre);
   pi=arcos(0)*2;
   s_01=J(n,1,0);
   h=4; * Bandwidth;
   p_01=p_01/2; * <- Correctly scale SAS periodogram;
   p_01=p_01/errvar; * Scale by error variance to give standard area across centres;
* Calculate weights;
   weight=J(1,h+h+1,0);
   do count=-h to h;
*      weight[1,count+h+1]=(h-abs(count))/h; * Triangular window;
      weight[1,count+h+1]=0.5*(1+cos(pi*count/h)); * Hanning window;
   end;
   sumw=weight*J(h+h+1,1,1);
* Mirror the data at the edges;
   head=J(h,1,0); tail=J(h,1,0);
   do count=0 to h-1;
      head[count+1,1]=p_01[h-count+1,1];
      tail[count+1,1]=p_01[n-count-1,1];
   end;
   pm_01=head//p_01//tail;
   do count=1 to n;
      s_01[count,1]=(weight*pm_01[h+count-h:h+count+h])/sumw;
   end;
* Output data;
   toout=centre||runit||period||freq||p_01||s_01;
   varnames={'centre' 'runit' 'period' 'freq' 'p_01' 's_01'};
   create work.spec from toout[colname=varnames];
   append from toout;
quit;
*goptions reset=all ftext=centxi htext=3 gunit=pct colors=(black) border;
filename graph1 "U:\Research\Projects\ihbi\aushsi\aushsi_barnetta\meta.research\reproducibility.challenge\updated_files\plots\sp&cent._&repunit..eps";
goptions reset=all ftext=centxi htext=3 gunit=pct colors=(black) gunit=pct noborder
    gsfname=graph1 noprompt gsfmode=replace device=PSLEPSF fontres=presentation dash;
symbol1 i=join color=grey value=NONE line=1;
symbol2 i=join color=black value=NONE line=2 width=4;
*legend1 value=(f=greek 'I(w)' 's(w)') label=NONE position=(top right inside) across=1 mode=share;
* Axes for period;
axis1 minor=NONE label=('Period') major=(h=2.5) order=(2 to 24 by 2) value=(h=2.5); *<-period;
axis2 minor=NONE label=(a=90 'I(f)') major=(h=2.5) value=(h=2.5); *<I(w);
%cntrname(&cent.,&repunit.);
title; * No title for final output;
data work.chop;
   set work.spec;
   if freq>0;
run;
proc gplot data=work.chop;
*   plot p_01*period=1 s_01*period=2 / noframe overlay haxis=axis1 vaxis=axis2 href=12 legend=legend1;
   plot p_01*period=1 / noframe haxis=axis1 vaxis=axis2 href=12; * Just the periodogram;
run; quit;
* Append periodogram data;
proc append base=work.allperi data=work.chop;
run;
%mend perisers;
